#!name=Youtube/Music
#!desc=Suitable for Youtube & Youtube Music (IOS >= 15) LU:16/6/24

[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT

[URL Rewrite]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad _ REJECT-IMG

[Script]
youtube.request = type=http-request,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|reel\/reel_watch_sequence|get_watch),requires-body=1,max-size=-1,binary-body-mode=1,engine=jsc,script-path=https://raw.githubusercontent.com/imtinaa/youtube/main/yrequest.js
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch),requires-body=1,max-size=-1,binary-body-mode=1,engine=jsc,script-path=https://raw.githubusercontent.com/imtinaa/youtube/main/yresponse.js,argument="{"lyricLang":"{{{LyricsLang}}}","captionLang":"{{{CaptionLang}}}","blockUpload":{{{BlockUploadBtn}}},"blockImmersive":{{{BlockImmersive}}},"debug":{{{Debug}}}}"

[MITM]
hostname = %APPEND% *.googlevideo.com, youtubei.googleapis.com
